### ISSUE TITLE
SIGSEGV when reading from named pipe

### ISSUE THREAD

**Issue by schweikert** [google/mtail#109]
I read in #58 that named pipes should be supported, but I am getting segmentation violation errors when trying to use one:

    # mtail -logtostderr -logs /var/run/test.fifo -progs /etc/mtail
    I1018 10:02:42.950220    7831 main.go:102] mtail version 3.0.0-rc4 git revision 2 go version go1.8.3
    I1018 10:02:42.950453    7831 main.go:103] Commandline: ["mtail" "-logtostderr" "-logs" "/var/run/test.fifo" "-progs" "/etc/mtail"]
    I1018 10:02:42.951016    7831 checker.go:79] found sym &{lines 0 typeVar4 rsyslog.mtail:8:9-13 <nil> 0}
    I1018 10:02:42.951147    7831 loader.go:206] Loaded program rsyslog.mtail
    I1018 10:02:42.951164    7831 loader.go:225] Program rsyslog.mtail has goroutine marker 0x72737973
    I1018 10:02:42.951182    7831 vm.go:753] Starting program rsyslog.mtail
    I1018 10:02:42.951195    7831 loader.go:229] Started rsyslog.mtail
    I1018 10:02:44.567205    7831 tail.go:363] Tailing /var/run/test.fifo
    I1018 10:02:44.567674    7831 tail.go:416] error on partial read of /var/run/test.fifo (fd &{0xc4200f9280}): EOF
    I1018 10:02:44.567865    7831 mtail.go:216] Listening on port :3903
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x46d6b2]

    goroutine 28 [running]:
    bytes.(*Buffer).WriteByte(0x0, 0x62, 0x7, 0x0)
        /usr/lib/golang/src/bytes/buffer.go:237 +0x22
    bytes.(*Buffer).WriteRune(0x0, 0x62, 0x1000, 0x62, 0x1)
        /usr/lib/golang/src/bytes/buffer.go:249 +0x10b
    github.com/google/mtail/tailer.(*Tailer).read(0xc420150120, 0xa25080, 0xc42000e0b8, 0x0, 0xa75a80, 0xc420077801)
        /home/builder/rpmbuild/BUILD/src/github.com/google/mtail/tailer/tail.go:204 +0x133
    github.com/google/mtail/tailer.(*Tailer).handleLogUpdate(0xc420150120, 0xc4200f9340, 0x12)
        /home/builder/rpmbuild/BUILD/src/github.com/google/mtail/tailer/tail.go:180 +0x151
    github.com/google/mtail/tailer.(*Tailer).run(0xc420150120, 0xc420060a80)
        /home/builder/rpmbuild/BUILD/src/github.com/google/mtail/tailer/tail.go:376 +0x215
    created by github.com/google/mtail/tailer.New
        /home/builder/rpmbuild/BUILD/src/github.com/google/mtail/tailer/tail.go:98 +0x298

**Comment by schweikert** [comment]
Note that the problem is not related to the EOF reported. That was caused by my testing. I get the same error with a named pipe that has a writer that stays on it (so no EOF):

    # mtail -logtostderr -logs /var/run/mtail.fifo-rsyslog -progs /etc/mtail
    I1018 10:07:31.118160    8101 main.go:102] mtail version 3.0.0-rc4 git revision 2 go version go1.8.3
    I1018 10:07:31.118265    8101 main.go:103] Commandline: ["mtail" "-logtostderr" "-logs" "/var/run/mtail.fifo-rsyslog" "-progs" "/etc/mtail"]
    I1018 10:07:31.118742    8101 checker.go:79] found sym &{lines 0 typeVar4 rsyslog.mtail:8:9-13 <nil> 0}
    I1018 10:07:31.118879    8101 loader.go:206] Loaded program rsyslog.mtail
    I1018 10:07:31.118910    8101 loader.go:225] Program rsyslog.mtail has goroutine marker 0x72737973
    I1018 10:07:31.118930    8101 vm.go:753] Starting program rsyslog.mtail
    I1018 10:07:31.118942    8101 loader.go:229] Started rsyslog.mtail
    I1018 10:07:31.119152    8101 tail.go:363] Tailing /var/run/mtail.fifo-rsyslog
    I1018 10:07:31.137307    8101 mtail.go:216] Listening on port :3903
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x46d6b2]

    goroutine 26 [running]:
    bytes.(*Buffer).WriteByte(0x0, 0x32, 0x18d, 0x0)
        /usr/lib/golang/src/bytes/buffer.go:237 +0x22
    bytes.(*Buffer).WriteRune(0x0, 0x32, 0x1000, 0x32, 0x1)
        /usr/lib/golang/src/bytes/buffer.go:249 +0x10b
    github.com/google/mtail/tailer.(*Tailer).read(0xc42014c120, 0xa25080, 0xc42007e078, 0x0, 0xa75a80, 0xc420081001)
        /home/builder/rpmbuild/BUILD/src/github.com/google/mtail/tailer/tail.go:204 +0x133
    github.com/google/mtail/tailer.(*Tailer).handleLogUpdate(0xc42014c120, 0xc42007ab60, 0x1b)
        /home/builder/rpmbuild/BUILD/src/github.com/google/mtail/tailer/tail.go:180 +0x151
    github.com/google/mtail/tailer.(*Tailer).run(0xc42014c120, 0xc420078960)
        /home/builder/rpmbuild/BUILD/src/github.com/google/mtail/tailer/tail.go:376 +0x215
    created by github.com/google/mtail/tailer.New
        /home/builder/rpmbuild/BUILD/src/github.com/google/mtail/tailer/tail.go:98 +0x298
