### ISSUE TITLE
Incorrect del usage should be detected at compile time

### ISSUE THREAD

**Issue by ferringb** [google/mtail#113]
In experimenting with the del syntax for #112, I noticed a spot where the parser could flag an error before starting, but instead it explodes in runtime.  Consider the following program:

```
gauge test by x, y
/.*/ {
  del test["x"]
  test["x"]["y"]
}
```

In that case, I was trying to force all submetrics of test["x"] to be wiped- IE, wipe "anything with label x, irregardless of what y is".  That's kind of horrible, but as I said, it was a test.

Syntax parsing considers that valid despite the # of dimensions used for the del invocation not matching the # of dimensions used for the type definition of test.  If that is ran, one has mtail blow up in their face like thus:

```
I1020 15:52:05.353996   32441 main.go:102] mtail version  git revision 81848d1b63a2ccc4f82eab3345069a5b10d51c88 go version go1.9.1
I1020 15:52:05.354041   32441 main.go:103] Commandline: ["mtail" "--logtostderr" "--progs" "test.mtail" "--logs" "/var/lib/backuppc/log/LOG" "-one_shot"]
I1020 15:52:05.354207   32441 checker.go:79] found sym &{test 0 typeVar4❌typeVar5❌typeVar6 test.mtail:1:7-10 <nil> 0}
I1020 15:52:05.354236   32441 checker.go:79] found sym &{test 0 typeVar4❌typeVar5❌typeVar6 test.mtail:1:7-10 <nil> 0}
I1020 15:52:05.354266   32441 codegen.go:74] Incomplete type typeVar9 for &vm.declNode{pos:vm.position{filename:"test.mtail", line:0, startcol:6, endcol:9}, name:"test", hidden:false, keys:[]string{"x", "y"}, kind:2, exportedName:"", sym:(*vm.Symbol)(0xc4201682d0)}
I1020 15:52:05.354313   32441 loader.go:206] Loaded program test.mtail
I1020 15:52:05.354322   32441 loader.go:225] Program test.mtail has goroutine marker 0x74657374
I1020 15:52:05.354341   32441 vm.go:753] Starting program test.mtail
I1020 15:52:05.354350   32441 loader.go:229] Started test.mtail
I1020 15:52:05.354530   32441 vm.go:197] test.mtail: Runtime error: panic in thread &vm.thread{pc:6, match:true, matched:false, matches:map[int][]string{0:[]string{"2017-10-20 01:00:00 Running 8 BackupPC_nightly jobs from 0..15 (out of 0..15)"}}, time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, stack:[]interface {}{}} at instr "{del 2}": runtime error: index out of range
I1020 15:52:05.354627   32441 vm.go:198] VM stack:
goroutine 23 [running]:
runtime/debug.Stack(0xc4201aa100, 0x3f, 0xc42005c780)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/google/mtail/vm.(*VM).errorf(0xc4201ac1e0, 0x85ca22, 0x23, 0xc42005c780, 0x3, 0x3)
	/cfsetup_build/mtail/tmp/build/gopath/src/github.com/google/mtail/vm/vm.go:198 +0xe1
github.com/google/mtail/vm.(*VM).execute.func1(0xc4201ac1e0, 0xc420168500, 0x1f, 0x7b8180, 0xc420176350)
	/cfsetup_build/mtail/tmp/build/gopath/src/github.com/google/mtail/vm/vm.go:405 +0x14f
panic(0x7dbb40, 0xa78410)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/google/mtail/vm.(*thread).Pop(...)
	/cfsetup_build/mtail/tmp/build/gopath/src/github.com/google/mtail/vm/vm.go:190
github.com/google/mtail/vm.(*VM).execute(0xc4201ac1e0, 0xc420168500, 0x1f, 0x7b8180, 0xc420176350)
	/cfsetup_build/mtail/tmp/build/gopath/src/github.com/google/mtail/vm/vm.go:423 +0x4ef7
github.com/google/mtail/vm.(*VM).processLine(0xc4201ac1e0, 0xc4200b2300)
	/cfsetup_build/mtail/tmp/build/gopath/src/github.com/google/mtail/vm/vm.go:740 +0x166
github.com/google/mtail/vm.(*VM).Run(0xc4201ac1e0, 0x74657374, 0xc42017a420, 0xc42017a480, 0xc42017a4e0)
	/cfsetup_build/mtail/tmp/build/gopath/src/github.com/google/mtail/vm/vm.go:758 +0xff
created by github.com/google/mtail/vm.(*Loader).CompileAndRun
	/cfsetup_build/mtail/tmp/build/gopath/src/github.com/google/mtail/vm/loader.go:227 +0x70f
I1020 15:52:05.354640   32441 vm.go:199] Dumping vm state
I1020 15:52:05.354645   32441 vm.go:200] Name: test.mtail
I1020 15:52:05.354650   32441 vm.go:201] Input: &tailer.LogLine{Filename:"/var/lib/backuppc/log/LOG", Line:"2017-10-20 01:00:00 Running 8 BackupPC_nightly jobs from 0..15 (out of 0..15)"}
I1020 15:52:05.354663   32441 vm.go:202] Thread:
I1020 15:52:05.354666   32441 vm.go:203]  PC 5
I1020 15:52:05.354671   32441 vm.go:204]  Match true
I1020 15:52:05.354676   32441 vm.go:205]  Matched false
I1020 15:52:05.354681   32441 vm.go:206]  Matches map[0:[2017-10-20 01:00:00 Running 8 BackupPC_nightly jobs from 0..15 (out of 0..15)]]
I1020 15:52:05.354688   32441 vm.go:207]  Timestamp 0001-01-01 00:00:00 +0000 UTC
I1020 15:52:05.354702   32441 vm.go:208]  Stack []
I1020 15:52:05.354765   32441 vm.go:209] Prog: test.mtail
Metrics
        0 Metric: name=test program=test.mtail kind=Gauge type=Int hidden=false keys=[x y] labelvalues=[] source=test.mtail:1:7-10
Regexps
        0 /.*/
Strings
        0 "x"
        1 "x"
        2 "y"
 disasm  l         op  opnd
         0      match     0
         1        jnm    11
         2 setmatched false
         3        str     0
         4      mload     0
         5        del     2
         6        str     1
         7        str     2
         8      mload     0
         9      dload     2
        10 setmatched  true
I1020 15:52:05.355094   32441 mtail.go:251] Shutdown requested.
I1020 15:52:05.355144   32441 log_watcher.go:74] Shutting down log watcher.
I1020 15:52:05.355180   32441 tail.go:404] Shutting down tailer.
I1020 15:52:05.355192   32441 loader.go:364] Shutting down loader.
I1020 15:52:05.355237   32441 log_watcher.go:74] Shutting down log watcher.
I1020 15:52:05.355252   32441 vm.go:760] Stopping program test.mtail
I1020 15:52:05.355266   32441 mtail.go:264] All done.
Metrics store:{
  "test": [
    {
      "Name": "test",
      "Program": "test.mtail",
      "Kind": 2,
      "Type": 0,
      "Keys": [
        "x",
        "y"
      ]
    }
  ]
}
```

I doubt that the syntax I tried should work- although it would be useful if it did for whatever other abuses I can think up- but that shouldn't explode at run time, it should explode at parse time.  We have the necessary information to detect this in the ast- or that's my understanding, thus why I think this should be a parse time failure.

**Comment by jaqx0r** [comment]
This is a good bug. Thanks! I know without looking that it's because of
poor validation in the del handler, which I don't like very much and also
is not well tested.
