### ISSUE TITLE
strptime layout should be validated during compilation, not at runtime

### ISSUE THREAD

**Issue by ferringb** [google/mtail#115]
This is related to #112; specifically my broken attempt at writing a strptime parse of that timestamp.

My understanding of mtail strptime is that it's just a shim over golang's time.Parse; time.Parse explodes in your face if you feed it a layout it doesn't understand.  Consider the following program for parsing backuppc log timestamps.  Note that strptime invocation is wrong (and yep, I didn't know the rules when I first wrote this):

```
def parsetimestamp {
  /^(?P<datetime>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}) / {
    strptime($datetime, "2017-10-16 06:50:25")
  }
  next
}

@parsetimestamp {
  gauge test
  // {
    test = 1
  }
}
```
That explodes at runtime:
```
I1020 16:10:03.148367   14515 main.go:102] mtail version  git revision 81848d1b63a2ccc4f82eab3345069a5b10d51c88 go version go1.9.1
I1020 16:10:03.148412   14515 main.go:103] Commandline: ["mtail" "--logtostderr" "--progs" "test.mtail" "--logs" "/home/brian/log2" "-one_shot"]
I1020 16:10:03.148755   14515 checker.go:79] found sym &{test 0 typeVar5 test.mtail:10:9-12 <nil> 0}
I1020 16:10:03.148841   14515 loader.go:206] Loaded program test.mtail
I1020 16:10:03.148852   14515 loader.go:225] Program test.mtail has goroutine marker 0x74657374
I1020 16:10:03.148878   14515 vm.go:753] Starting program test.mtail
I1020 16:10:03.148889   14515 loader.go:229] Started test.mtail
I1020 16:10:03.149115   14515 vm.go:197] test.mtail: Runtime error: strptime (2017-10-16 06:50:25, 2017-10-17 18:00:00, UTC) failed: parsing time "2017-10-17 18:00:00": month out of range
I1020 16:10:03.149182   14515 vm.go:198] VM stack:
goroutine 26 [running]:
runtime/debug.Stack(0xc4201b2400, 0x3c, 0xc42005c888)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/google/mtail/vm.(*VM).errorf(0xc4200f8fa0, 0x85b499, 0x20, 0xc42005c888, 0x4, 0x4)
        /cfsetup_build/mtail/tmp/build/gopath/src/github.com/google/mtail/vm/vm.go:198 +0xe1
github.com/google/mtail/vm.(*VM).ParseTime(0xc4200f8fa0, 0xc4200b4480, 0x13, 0xc42011a0a0, 0x13, 0x7b8100, 0xc4200b2be0, 0x2)
        /cfsetup_build/mtail/tmp/build/gopath/src/github.com/google/mtail/vm/vm.go:383 +0x208
github.com/google/mtail/vm.(*VM).execute(0xc4200f8fa0, 0xc4200b8960, 0x6, 0x7b8180, 0xc4200b2be0)
        /cfsetup_build/mtail/tmp/build/gopath/src/github.com/google/mtail/vm/vm.go:530 +0x3f1d
github.com/google/mtail/vm.(*VM).processLine(0xc4200f8fa0, 0xc42014c9e0)
        /cfsetup_build/mtail/tmp/build/gopath/src/github.com/google/mtail/vm/vm.go:740 +0x166
github.com/google/mtail/vm.(*VM).Run(0xc4200f8fa0, 0x74657374, 0xc4200d6540, 0xc4200d65a0, 0xc4200d6600)
        /cfsetup_build/mtail/tmp/build/gopath/src/github.com/google/mtail/vm/vm.go:758 +0xff
created by github.com/google/mtail/vm.(*Loader).CompileAndRun
        /cfsetup_build/mtail/tmp/build/gopath/src/github.com/google/mtail/vm/loader.go:227 +0x70f
I1020 16:10:03.149206   14515 vm.go:199] Dumping vm state
I1020 16:10:03.149210   14515 vm.go:200] Name: test.mtail
I1020 16:10:03.149214   14515 vm.go:201] Input: &tailer.LogLine{Filename:"/home/brian/log2", Line:"2017-10-17 18:00:00 Deleted host 36ndb1.cfops.it from backup list"}
I1020 16:10:03.149227   14515 vm.go:202] Thread:
I1020 16:10:03.149230   14515 vm.go:203]  PC 6
I1020 16:10:03.149234   14515 vm.go:204]  Match true
I1020 16:10:03.149238   14515 vm.go:205]  Matched false
I1020 16:10:03.149242   14515 vm.go:206]  Matches map[0:[2017-10-17 18:00:00  2017-10-17 18:00:00]]
I1020 16:10:03.149250   14515 vm.go:207]  Timestamp 0001-01-01 00:00:00 +0000 UTC
I1020 16:10:03.149265   14515 vm.go:208]  Stack []
I1020 16:10:03.149357   14515 vm.go:209] Prog: test.mtail
Metrics
        0 Metric: name=test program=test.mtail kind=Gauge type=Int hidden=false keys=[] labelvalues=[] source=test.mtail:10:9-12
Regexps
        0 /^(?P<datetime>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}) /
        1 //
Strings
        0 "2017-10-16 06:50:25"
 disasm  l         op  opnd
         0      match     0
         1        jnm     8
         2 setmatched false
         3       push     0
         4     capref     1
         5        str     0
         6   strptime     2
         7 setmatched  true
         8      match     1
         9        jnm    16
        10 setmatched false
        11      mload     0
        12      dload     0
        13       push     1
        14       iset <nil>
        15 setmatched  true
```

However, if I understand golang's nice little hack for the layout, it should be possible to detect this at parse time- assuming that the layout passed to strptime is a string constant, and not a variable.

The following go snippet shows what I mean: https://play.golang.org/p/o7DstQtQom .  Note that feeding the layout back in as the value to parse explodes.  If the layout cannot parse itself, then the layout is broken- or that's my understanding.  See https://play.golang.org/p/qdBNesf5sn for an example; note the lack of an error thrown.

If the layout can always parse itself- which afaik, is an intentional design choice for time.Parse- we can extend the compilation steps to do a validation check of the layout given if it's a string constant.

Having that check at parse/compile time- where possible- would make validation easier for folks learning mtail, or for things like #114

**Comment by jaqx0r** [comment]
Thanks for the suggestion!  I didn't realise you could validate the format string that way, makes total sense!

**Comment by jaqx0r** [comment]
Ah it's not that easy.  A layout string can contain an underscore to indicate:

```
  // Within the format string, an underscore _ represents a space that may be
  // replaced by a digit if the following number (a day) has two digits; for
  // compatibility with fixed-width Unix time formats.
```

so one more change to remove underscores from the input.

**Comment by jaqx0r** [comment]
and for some reason, Z07:00 suffix rquired by time.RFC3339 is not allowed... oh it's only for printing in the UTC time, but offsets required otherwise.
