### ISSUE TITLE
Parsing issue: interface conversion: interface {} is int64, not string

### ISSUE THREAD

**Issue by lukaszzalewski** [google/mtail#196]
This is happening when the app starts up and hits the first log line. I'm having some trouble identifying what the issue is. 

I believe this is due to the `(?P<response_time>\d+)` portion of the regex since if i change it to `(?P<response_time>\d+\.\d+)` the error changes from int64 to float64. Any help that would point to the issue would be great. Thanks!

mtail startup:
`mtail -logtostderr -poll_interval 5s -progs /go/parsers/main.mtail -logs '/var/log/containers/main-{{ env }}-*'"`

mtail Config:
```
counter main_line_counter
counter main_status by response_code
counter main_http_response_time by le

/^\{\"log\"\:\"\S+ \S+ \S+ \[\d{2}\/\w{3}\/\d{4}:\d{2}:\d{2}:\d{2} [\+|-]\d{4}\] \\"[A-Z]+ \S+ HTTP\/[0-9\.]+\\" (?P<response_code>\d{3}) \S+ \\".*\\" \\".*\\" (?P<response_time>\d+)\.\d+ .*$/ {

    main_line_counter++

    $response_code =~ /2../ {
        main_status["2xx"]++
    }
    
    $response_code =~ /3../ {
        main_status["3xx"]++
    }
    
    $response_code =~ /4../ {
        main_status["4xx"]++
    }
    
    $response_code =~ /4../ {
        main_status["5xx"]++
    }

    $response_time <= 5 {
        main_http_response_time["005"]++
    }

    $response_time > 5 && $response_time <= 10 {
        main_http_response_time["010"]++
    }

    $response_time > 10 && $response_time <= 25 {
        main_http_response_time["025"]++
    }

    $response_time > 25 && $response_time <= 50 {
        main_http_response_time["050"]++
    }

    $response_time > 50 && $response_time <= 100 {
        main_http_response_time["100"]++
    }

    $response_time > 100 && $response_time <= 200 {
        main_http_response_time["200"]++
    }

    $response_time > 200 && $response_time <= 500 {
        main_http_response_time["500"]++
    }

    $response_time > 500 {
        main_http_response_time["inf"]++
    }
}
```
Log:
```
I1207 19:08:57.497174       1 mtail.go:93] mtail version v3.0.0-rc17-106-g80b5891 git revision 80b5891d67d0961be6b4438f1ee6065f7c18a4a4 go version go1.11.2 go arch amd64 go os linux
I1207 19:08:57.497214       1 mtail.go:94] Commandline: ["mtail" "-logtostderr" "-poll_interval" "5s" "-progs" "/go/parsers/main.mtail" "-logs" "/var/log/containers/main-prod-*"]
I1207 19:08:57.497971       1 loader.go:220] Loaded program main.mtail
I1207 19:08:57.497986       1 loader.go:239] Program main.mtail has goroutine marker 0x7464622e
I1207 19:08:57.498010       1 vm.go:749] Starting program main.mtail
I1207 19:08:57.498034       1 loader.go:243] Started main.mtail
I1207 19:08:57.498177       1 tail.go:274] Tailing /var/log/containers/main-prod-deployment-555d94c777-6dl4b_default_main-prod-416d769c9071131ac98547165aaaa22e758a4ea5d057cd048ee52bc3fd271377.log
I1207 19:08:57.498234       1 tail.go:274] Tailing /var/log/containers/main-prod-deployment-555d94c777-qjqfl_default_main-prod-87f6a0818504be0c7d9898c176477133516b2fca6df34f5f20134c65e62d2331.log
I1207 19:08:57.498358       1 mtail.go:239] Listening on port :3903
I1207 19:08:57.553349       1 vm.go:80] main.mtail: Runtime error: panic in thread &vm.thread{pc:10, matched:false, matches:map[int][]string{0:[]string{"{\"log\":\"00.00.00.00 - - [07/Dec/2018:19:08:57 +0000] \\\"GET /some-url HTTP/1.1\\\" 304 - \\\"https://some-other-url?ref=scroll\\\" \\\"Mozilla/5.0 (iPad; CPU OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1\\\" 16.683 ms\\n\",\"stream\":\"stdout\",\"time\":\"2018-12-07T19:08:57.552897699Z\"}", "304", "16"}}, time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, stack:[]interface {}{}} at instr "{smatch 1}": interface conversion: interface {} is int64, not string
I1207 19:08:57.553608       1 vm.go:81] VM stack:
goroutine 12 [running]:
runtime/debug.Stack(0xc0001fa080, 0x3e, 0xc00021b670)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/google/mtail/internal/vm.(*VM).errorf(0xc0000a9400, 0x8850f1, 0x23, 0xc00021b670, 0x3, 0x3)
	/go/src/github.com/google/mtail/internal/vm/vm.go:81 +0x113
github.com/google/mtail/internal/vm.(*VM).execute.func1(0xc0000a9400, 0xc0000c80a0, 0x3, 0x7da760, 0xc000178ab8)
	/go/src/github.com/google/mtail/internal/vm/vm.go:286 +0x142
panic(0x805a40, 0xc000138360)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/google/mtail/internal/vm.(*VM).execute(0xc0000a9400, 0xc0000c80a0, 0x3, 0x7da760, 0xc000178ab8)
	/go/src/github.com/google/mtail/internal/vm/vm.go:310 +0x61e3
github.com/google/mtail/internal/vm.(*VM).processLine(0xc0000a9400, 0xc0000c60e0)
	/go/src/github.com/google/mtail/internal/vm/vm.go:734 +0x140
github.com/google/mtail/internal/vm.(*VM).Run(0xc0000a9400, 0x7464622e, 0xc000027440, 0xc0000274a0, 0xc000027500)
	/go/src/github.com/google/mtail/internal/vm/vm.go:753 +0xf5
created by github.com/google/mtail/internal/vm.(*Loader).CompileAndRun
	/go/src/github.com/google/mtail/internal/vm/loader.go:241 +0x70d
I1207 19:08:57.553673       1 vm.go:82] Dumping vm state
I1207 19:08:57.553712       1 vm.go:83] Name: main.mtail
I1207 19:08:57.553739       1 vm.go:84] Input: &logline.LogLine{Filename:"/var/log/containers/main-prod-deployment-555d94c777-qjqfl_default_main-prod-87f6a0818504be0c7d9898c176477133516b2fca6df34f5f20134c65e62d2331.log", Line:"{\"log\":\"00.00.00.00 - - [07/Dec/2018:19:08:57 +0000] \\\"GET /some-url HTTP/1.1\\\" 304 - \\\"https://some-other-url?ref=scroll\\\" \\\"Mozilla/5.0 (iPad; CPU OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1\\\" 16.683 ms\\n\",\"stream\":\"stdout\",\"time\":\"2018-12-07T19:08:57.552897699Z\"}"}
I1207 19:08:57.553802       1 vm.go:85] Thread:
I1207 19:08:57.553856       1 vm.go:86]  PC 9
I1207 19:08:57.553884       1 vm.go:87]  Matched false
I1207 19:08:57.553910       1 vm.go:88]  Matches map[0:[{"log":"00.00.00.00 - - [07/Dec/2018:19:08:57 +0000] \"GET /some-url HTTP/1.1\" 304 - \"https://some-other-url?ref=scroll\" \"Mozilla/5.0 (iPad; CPU OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1\" 16.683 ms\n","stream":"stdout","time":"2018-12-07T19:08:57.552897699Z"} 304 16]]
I1207 19:08:57.553947       1 vm.go:89]  Timestamp 0001-01-01 00:00:00 +0000 UTC
I1207 19:08:57.554025       1 vm.go:90]  Stack []
I1207 19:08:57.554604       1 vm.go:91] Prog: main.mtail
Metrics
        0 Metric: name=main_line_counter program=main.mtail kind=Counter type=Int hidden=false keys=[] labelvalues=[LabelValue: [] 1@1544209737553261490] source=main.mtail:1:9-24
        1 Metric: name=main_status program=main.mtail kind=Counter type=Int hidden=false keys=[response_code] labelvalues=[] source=main.mtail:2:9-18
        2 Metric: name=main_http_response_time program=main.mtail kind=Counter type=Int hidden=false keys=[le] labelvalues=[] source=main.mtail:3:9-30
Regexps
        0 /^\{\"log\"\:\"\S+ \S+ \S+ \[\d{2}/\w{3}/\d{4}:\d{2}:\d{2}:\d{2} [\+|-]\d{4}\] \\"[A-Z]+ \S+ HTTP/[0-9\.]+\\" (?P<response_code>\d{3}) \S+ \\".*\\" \\".*\\" (?P<response_time>\d+)\.\d+ .*$/
        1 /2../
        2 /3../
        3 /4../
        4 /4../
Strings
        0 "2xx"
        1 "3xx"
        2 "4xx"
        3 "5xx"
        4 "005"
        5 "010"
        6 "025"
        7 "050"
        8 "100"
        9 "200"
       10 "500"
       11 "inf"
 disasm   l         op  opnd
          0      match     0
          1        jnm   263
          2 setmatched false
          3      mload     0
          4      dload     0
          5        inc <nil>
          6       push     0
          7     capref     1
          8        s2i <nil>
          9     smatch     1
         10        jnm    17
         11 setmatched false
         12        str     0
         13      mload     1
         14      dload     1
         15        inc <nil>
         16 setmatched  true
         17       push     0
         18     capref     1
         19        s2i <nil>
         20     smatch     2
         21        jnm    28
         22 setmatched false
         23        str     1
         24      mload     1
         25      dload     1
         26        inc <nil>
         27 setmatched  true
         28       push     0
         29     capref     1
         30        s2i <nil>
         31     smatch     3
         32        jnm    39
         33 setmatched false
         34        str     2
         35      mload     1
         36      dload     1
         37        inc <nil>
         38 setmatched  true
         39       push     0
         40     capref     1
         41        s2i <nil>
         42     smatch     4
         43        jnm    50
         44 setmatched false
         45        str     3
         46      mload     1
         47      dload     1
         48        inc <nil>
         49 setmatched  true
         50       push     0
         51     capref     2
         52        s2i <nil>
         53       push     5
         54       icmp     1
         55         jm    58
         56       push  true
         57        jmp    59
         58       push false
         59        jnm    66
         60 setmatched false
         61        str     4
         62      mload     2
         63      dload     1
         64        inc <nil>
         65 setmatched  true
         66       push     0
         67     capref     2
         68        s2i <nil>
         69       push     5
         70       icmp     1
         71        jnm    74
         72       push  true
         73        jmp    75
         74       push false
         75        jnm    88
         76       push     0
         77     capref     2
         78        s2i <nil>
         79       push    10
         80       icmp     1
         81         jm    84
         82       push  true
         83        jmp    85
         84       push false
         85        jnm    88
         86       push  true
         87        jmp    89
         88       push false
         89        jnm    96
         90 setmatched false
         91        str     5
         92      mload     2
         93      dload     1
         94        inc <nil>
         95 setmatched  true
         96       push     0
         97     capref     2
         98        s2i <nil>
         99       push    10
        100       icmp     1
        101        jnm   104
        102       push  true
        103        jmp   105
        104       push false
        105        jnm   118
        106       push     0
        107     capref     2
        108        s2i <nil>
        109       push    25
        110       icmp     1
        111         jm   114
        112       push  true
        113        jmp   115
        114       push false
        115        jnm   118
        116       push  true
        117        jmp   119
        118       push false
        119        jnm   126
        120 setmatched false
        121        str     6
        122      mload     2
        123      dload     1
        124        inc <nil>
        125 setmatched  true
        126       push     0
        127     capref     2
        128        s2i <nil>
        129       push    25
        130       icmp     1
        131        jnm   134
        132       push  true
        133        jmp   135
        134       push false
        135        jnm   148
        136       push     0
        137     capref     2
        138        s2i <nil>
        139       push    50
        140       icmp     1
        141         jm   144
        142       push  true
        143        jmp   145
        144       push false
        145        jnm   148
        146       push  true
        147        jmp   149
        148       push false
        149        jnm   156
        150 setmatched false
        151        str     7
        152      mload     2
        153      dload     1
        154        inc <nil>
        155 setmatched  true
        156       push     0
        157     capref     2
        158        s2i <nil>
        159       push    50
        160       icmp     1
        161        jnm   164
        162       push  true
        163        jmp   165
        164       push false
        165        jnm   178
        166       push     0
        167     capref     2
        168        s2i <nil>
        169       push   100
        170       icmp     1
        171         jm   174
        172       push  true
        173        jmp   175
        174       push false
        175        jnm   178
        176       push  true
        177        jmp   179
        178       push false
        179        jnm   186
        180 setmatched false
        181        str     8
        182      mload     2
        183      dload     1
        184        inc <nil>
        185 setmatched  true
        186       push     0
        187     capref     2
        188        s2i <nil>
        189       push   100
        190       icmp     1
        191        jnm   194
        192       push  true
        193        jmp   195
        194       push false
        195        jnm   208
        196       push     0
        197     capref     2
        198        s2i <nil>
        199       push   200
        200       icmp     1
        201         jm   204
        202       push  true
        203        jmp   205
        204       push false
        205        jnm   208
        206       push  true
        207        jmp   209
        208       push false
        209        jnm   216
        210 setmatched false
        211        str     9
        212      mload     2
        213      dload     1
        214        inc <nil>
        215 setmatched  true
        216       push     0
        217     capref     2
        218        s2i <nil>
        219       push   200
        220       icmp     1
        221        jnm   224
        222       push  true
        223        jmp   225
        224       push false
        225        jnm   238
        226       push     0
        227     capref     2
        228        s2i <nil>
        229       push   500
        230       icmp     1
        231         jm   234
        232       push  true
        233        jmp   235
        234       push false
        235        jnm   238
        236       push  true
        237        jmp   239
        238       push false
        239        jnm   246
        240 setmatched false
        241        str    10
        242      mload     2
        243      dload     1
        244        inc <nil>
        245 setmatched  true
        246       push     0
        247     capref     2
        248        s2i <nil>
        249       push   500
        250       icmp     1
        251        jnm   254
        252       push  true
        253        jmp   255
        254       push false
        255        jnm   262
        256 setmatched false
        257        str    11
        258      mload     2
        259      dload     1
        260        inc <nil>
        261 setmatched  true
        262 setmatched  true
```

**Comment by jaqx0r** [comment]
Oh you solved it?

The debugger could be more helpful here, but... If you look at the dumped
assembly and see where the PC is pointing when you see the crash, you can
work backwards to find the most recently loaded variable (capref) or metric
(mload) and see what it's referring to.

Then you might find the regular expression matches something it shouldn't,
or you're triggering a bug in the VM.

I'll be interested to know how you fixed the issue, so I can know if it's a
VM bug.
