### ISSUE TITLE
single "-" is errnoneously passed to parseInt in conditional

### ISSUE THREAD

**Issue by wpalmer** [google/mtail#228]
When matching a single "-" character, it is erroneously passed to parseInt when attempting to compare it against the "-" literal.

minimal program:
```
counter c

/(?P<x>-)/ {
    $x == "-" {
        c++
    }
}
```

against log file:
```
123 a
- b
```

running as: `/usr/bin/mtail --progs /etc/mtail --logs=/var/log/d.log --logtostderr --one_shot`

Results in: 
```
I0422 23:05:58.733416       1 main.go:94] mtail version  git revision  go version go1.10.8 go arch amd64 go os linux
I0422 23:05:58.733474       1 main.go:95] Commandline: ["/usr/bin/mtail" "--progs" "/etc/mtail" "--logs=/var/log/d.log" "--logtostderr" "--one_shot"]
I0422 23:05:58.734150       1 loader.go:220] Loaded program demo.mtail
I0422 23:05:58.734162       1 loader.go:239] Program demo.mtail has goroutine marker 0x64656d6f
I0422 23:05:58.734174       1 vm.go:763] Starting program demo.mtail
I0422 23:05:58.734180       1 loader.go:243] Started demo.mtail
I0422 23:05:58.734298       1 tail.go:246] Tailing /var/log/d.log
I0422 23:05:58.734305       1 mtail.go:358] Shutdown requested.
I0422 23:05:58.734344       1 vm.go:90] demo.mtail: Runtime error: strconv.ParseInt: parsing "-": invalid syntax
I0422 23:05:58.734372       1 vm.go:91] VM stack:
goroutine 49 [running]:
runtime/debug.Stack(0xc42005d5b8, 0x1e, 0xc42005dc08)
        /usr/lib/go/src/runtime/debug/stack.go:24 +0xa9
github.com/google/mtail/internal/vm.(*VM).errorf(0xc420194960, 0x5621153c18ff, 0x2, 0xc42005dc08, 0x1, 0x1)
        /go/src/github.com/google/mtail/internal/vm/vm.go:91 +0x115
github.com/google/mtail/internal/vm.(*VM).execute(0xc420194960, 0xc420170c30, 0x34, 0x0, 0x0)
        /go/src/github.com/google/mtail/internal/vm/vm.go:675 +0x2eee
github.com/google/mtail/internal/vm.(*VM).processLine(0xc420194960, 0xc4201d0ee0)
        /go/src/github.com/google/mtail/internal/vm/vm.go:748 +0x1a1
github.com/google/mtail/internal/vm.(*VM).Run(0xc420194960, 0x64656d6f, 0xc420176720, 0xc420176780, 0xc4201767e0)
        /go/src/github.com/google/mtail/internal/vm/vm.go:767 +0xf7
created by github.com/google/mtail/internal/vm.(*Loader).CompileAndRun
        /go/src/github.com/google/mtail/internal/vm/loader.go:241 +0x70c
I0422 23:05:58.734386       1 vm.go:92] Dumping vm state
I0422 23:05:58.734391       1 vm.go:93] Name: demo.mtail
I0422 23:05:58.734394       1 vm.go:94] Input: &logline.LogLine{Filename:"/var/log/d.log", Line:"- b"}
I0422 23:05:58.734404       1 vm.go:95] Thread:
I0422 23:05:58.734408       1 vm.go:96]  PC 5
I0422 23:05:58.734412       1 vm.go:97]  Matched false
I0422 23:05:58.734416       1 vm.go:98]  Matches map[0:[- -]]
I0422 23:05:58.734424       1 vm.go:99]  Timestamp 0001-01-01 00:00:00 +0000 UTC
I0422 23:05:58.734435       1 vm.go:100]  Stack []
I0422 23:05:58.734511       1 vm.go:101] Prog: demo.mtail
Metrics
        0 Metric: name=c program=demo.mtail kind=Counter type=Int hidden=false keys=[] labelvalues=[LabelValue: [] 0@0] source=demo.mtail:1:9 buckets=[]
Regexps
        0 /(?P<x>-)/
Strings
        0 "-"
 disasm  l         op  opnd
         0      match     0
         1        jnm    20
         2 setmatched false
         3       push     0
         4     capref     1
         5        s2i <nil>
         6        i2s <nil>
         7        str     0
         8       scmp     0
         9        jnm    12
        10       push  true
        11        jmp    13
        12       push false
        13        jnm    19
        14 setmatched false
        15      mload     0
        16      dload     0
        17        inc <nil>
        18 setmatched  true
        19 setmatched  true
I0422 23:05:58.734676       1 log_watcher.go:211] Shutting down log watcher.
I0422 23:05:58.734700       1 log_watcher.go:225] Closing events channels
I0422 23:05:58.734715       1 tail.go:287] Closing lines channel.
I0422 23:05:58.734724       1 tail.go:289] Shutting down tailer.
I0422 23:05:58.734739       1 loader.go:428] Shutting down loader.
I0422 23:05:58.734749       1 loader.go:435] Closing VM lines channels.
I0422 23:05:58.734758       1 vm.go:769] Stopping program demo.mtail
I0422 23:05:58.734785       1 mtail.go:386] END OF LINE
Metrics store:{
  "c": [
    {
      "Name": "c",
      "Program": "demo.mtail",
      "Kind": 1,
      "Type": 0,
      "LabelValues": [
        {
          "Value": {
            "Value": 0,
            "Time": 0
          }
        }
      ]
    }
  ]
}
```

I don't know why parseInt is being involved in this at all - I would expect that comparing against a string would always result in a string comparison.
This appears to be on the variable side, not on the string side. I have presently worked around this issue by capturing the string " - ", rather than "-", which runs / comparse as expected.

**Comment by jaqx0r** [comment]
Thanks for the report.  This was fun to debug!  parseInt was being called because the type checker thought that the capture group reference $x could be an Int, which it thought because "-" is part of an integer's string representation.  But a single "-" shouldn't match an Int -- that's now fixed.

**Comment by wpalmer** [comment]
Thanks for fixing this, I'll remove my work-around to verify this as soon
as I get a moment
