### ISSUE TITLE
Mtail process getting Killed

### ISSUE THREAD

**Issue by jakirpatel** [google/mtail#274]
Hi ,
Linux kernal: Linux 2.6.39-400.286.3.el6uek.x86_64
Its happening usually nowadays that the mtail processes are getting killed after certain time. The most recent error I was able to capture was:

```
panic: runtime error: index out of range

goroutine 11 [running]:
Log file created at: 2019/10/31 03:19:20
bytes.(*Buffer).WriteByte(0xc0003b7980, 0xc00034c736, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:272 +0xa6
bytes.(*Buffer).WriteRune(0xc0003b7980, 0x36, 0x9e8, 0x36, 0x1)
	/usr/local/go/src/bytes/buffer.go:282 +0x14d
github.com/google/mtail/internal/tailer.(*File).Read(0xc0000d5380, 0xacc8a0, 0xc0003b7aa0, 0x0, 0x0)
	/go/src/github.com/google/mtail/internal/tailer/file.go:208 +0x1a9
github.com/google/mtail/internal/tailer.(*Tailer).openLogPath(0xc0001e6e80, 0xc00049a000, 0x29, 0x1, 0x0, 0x0)
	/go/src/github.com/google/mtail/internal/tailer/tail.go:286 +0x425
github.com/google/mtail/internal/tailer.(*Tailer).handleCreateGlob(0xc0001e6e80, 0xacc8a0, 0xc0003b7800, 0xc00049a000, 0x29)
	/go/src/github.com/google/mtail/internal/tailer/tail.go:322 +0x392
github.com/google/mtail/internal/tailer.(*Tailer).ProcessFileEvent(0xc0001e6e80, 0xacc8a0, 0xc0003b7800, 0x2, 0xc00049a000, 0x29)
	/go/src/github.com/google/mtail/internal/tailer/tail.go:239 +0x180
github.com/google/mtail/internal/watcher.(*LogWatcher).sendWatchedEvent(0xc0000d5080, 0xc0004936b0, 0x2, 0xc00049a000, 0x29)
	/go/src/github.com/google/mtail/internal/watcher/log_watcher.go:97 +0x9c
github.com/google/mtail/internal/watcher.(*LogWatcher).sendEvent(0xc0000d5080, 0x2, 0xc00049a000, 0x29)
	/go/src/github.com/google/mtail/internal/watcher/log_watcher.go:91 +0xef
github.com/google/mtail/internal/watcher.(*LogWatcher).runEvents(0xc0000d5080)
	/go/src/github.com/google/mtail/internal/watcher/log_watcher.go:208 +0x1d2
created by github.com/google/mtail/internal/watcher.NewLogWatcher
	/go/src/github.com/google/mtail/internal/watcher/log_watcher.go:72 +0x10b
```

Startup:
```
#!/bin/bash

./mtail \
-poll_interval 500ms \
-port 3901 \
-progs progs/basketPerfLog.mtail \
-logs /rms/logs/bsktapiA/perfKVS/bsktapiA21.log \
-logs /rms/logs/bsktapiA/perfKVS/bsktapiA22.log \
-logs /rms/logs/bsktapiA/perfKVS/bsktapiA23.log \
-logs /rms/logs/bsktapiA/perfKVS/bsktapiA24.log \
```

Mtail version
```
mtail version v3.0.0-rc33 git revision aedde73f9c304e4d558a53ece22a5472c87a7fdb go version go1.12.7 go arch amd64 go os linux
```

FYI : There are no Kernel logs I can see on the server. Thats not good.

**Comment by jaqx0r** [comment]
Thanks for the report. Based on the traceback my guess is that some error
condition is triggered by the read and it's not being handled correctly.

**Comment by jakirpatel** [comment]
Is there any way to improve this ? @jaqx0r

**Comment by jaqx0r** [comment]
Without any more information at hand it's hard to say!   I can imagine two
paths to solve this : one is an audit of the code near where it's crashed
per your traceback, and the other is trying to build a reproducible test
case so we can observe the failure and study it.

**Comment by jakirpatel** [comment]
@jaqx0r  Thanks for your reply. 

I was running the process with nice value 19. 
```
#!/bin/bash

nice -n 19 ./mtail \
-poll_interval 200ms \
-port 3901 \
-progs progs/program.mtail \
-logs a.log \
```

After removing nice and adding the disable_fsnotify function it was running okay.
