### ISSUE TITLE
segfaults on 32-bit Debian architectures (i386, mipsel, armel, armhf)

### ISSUE THREAD

**Issue by anarcat** [google/mtail#313]
I have updated the mtail debian package to the latest RC here (rc35) and we're still seeing failures to build from source due to the test suite failing, but only on certain architectures.

The error seems to be consistent across architectures, as:

```
=== RUN   TestHandlePrometheus/histo
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12e5c]

goroutine 126 [running]:
runtime/internal/atomic.goLoad64(0x21bf52c, 0x0, 0x0)
	/usr/lib/go-1.14/src/runtime/internal/atomic/atomic_arm.go:131 +0x1c
github.com/google/mtail/internal/metrics/datum.(*Buckets).GetCount(...)
	/<<PKGBUILDDIR>>/build/src/github.com/google/mtail/internal/metrics/datum/buckets.go:60
github.com/google/mtail/internal/metrics/datum.GetBucketsCount(0x4988c0, 0x21bf500, 0x228e160, 0x1c)
	/<<PKGBUILDDIR>>/build/src/github.com/google/mtail/internal/metrics/datum/datum.go:222 +0x50
github.com/google/mtail/internal/exporter.(*Exporter).Collect(0x2284540, 0x2280480)
	/<<PKGBUILDDIR>>/build/src/github.com/google/mtail/internal/exporter/prometheus.go:69 +0x41c
github.com/prometheus/client_golang/prometheus.DescribeByCollect.func1(0x497a38, 0x2284540, 0x2280480)
	/<<PKGBUILDDIR>>/build/src/github.com/prometheus/client_golang/prometheus/collector.go:90 +0x2c
created by github.com/prometheus/client_golang/prometheus.DescribeByCollect
	/<<PKGBUILDDIR>>/build/src/github.com/prometheus/client_golang/prometheus/collector.go:89 +0x54
FAIL	github.com/google/mtail/internal/exporter	0.078s
?   	github.com/google/mtail/internal/logline	[no test files]
=== RUN   TestKindType
[...]
=== RUN   TestMakeBucket
--- FAIL: TestMakeBucket (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x804a96b]

goroutine 24 [running]:
testing.tRunner.func1.1(0x81b27c0, 0x83126d8)
	/usr/lib/go-1.14/src/testing/testing.go:940 +0x27c
testing.tRunner.func1(0x9d92320)
	/usr/lib/go-1.14/src/testing/testing.go:943 +0x349
panic(0x81b27c0, 0x83126d8)
	/usr/lib/go-1.14/src/runtime/panic.go:969 +0x122
runtime/internal/atomic.Load64(0x9d1e66c, 0x0, 0x40000000)
	/usr/lib/go-1.14/src/runtime/internal/atomic/asm_386.s:194 +0xb
github.com/google/mtail/internal/metrics/datum.(*Buckets).GetCount(...)
	/<<PKGBUILDDIR>>/build/src/github.com/google/mtail/internal/metrics/datum/buckets.go:60
github.com/google/mtail/internal/metrics/datum.GetBucketsCount(0x820aed0, 0x9d1e640, 0x0, 0x40000000)
	/<<PKGBUILDDIR>>/build/src/github.com/google/mtail/internal/metrics/datum/datum.go:222 +0x47
github.com/google/mtail/internal/metrics/datum_test.TestMakeBucket(0x9d92320)
	/<<PKGBUILDDIR>>/build/src/github.com/google/mtail/internal/metrics/datum/buckets_test.go:37 +0x20b
testing.tRunner(0x9d92320, 0x81de388)
	/usr/lib/go-1.14/src/testing/testing.go:991 +0xb4
created by testing.(*T).Run
	/usr/lib/go-1.14/src/testing/testing.go:1042 +0x2ad
FAIL	github.com/google/mtail/internal/metrics/datum	0.014s
=== RUN   TestHandleLogUpdates
```

The complete build logs are available for Debian here:

https://buildd.debian.org/status/fetch.php?pkg=mtail&arch=i386&ver=3.0.0%7Erc35-0.1&stamp=1587507894&raw=0
https://buildd.debian.org/status/fetch.php?pkg=mtail&arch=mipsel&ver=3.0.0%7Erc35-0.1&stamp=1587519228&raw=0
https://buildd.debian.org/status/fetch.php?pkg=mtail&arch=armhf&ver=3.0.0%7Erc35-0.1&stamp=1587506537&raw=0
https://buildd.debian.org/status/fetch.php?pkg=mtail&arch=armel&ver=3.0.0%7Erc35-0.1&stamp=1587506619&raw=0

I will probably just disable binary packages for those architectures for now, but it would be great if mtail could still run on those. Or it should be stated clearly that 32-bit architectures are out of scope.

Thanks!

**Comment by jaqx0r** [comment]
This is very strange.  I see from the build logs it's done with go 1.14.  Do you know if this is repeatable with other compiler versions?

**Comment by jaqx0r** [comment]
Ah I guess it's this: https://golang.org/pkg/sync/atomic/#pkg-note-BUG

I don't know for certain that these fields are aligned (I don't know that this is why they're causing the crash either.)
