### ISSUE TITLE
Runtime error: strconv.ParseInt: parsing "-": invalid syntax

### ISSUE THREAD

**Issue by cirolini** [google/mtail#315]
Hi, I am trying to update the version of mtail that I use in my environments from version (mtail version v3.0.0-rc15 git revision 2991023ad62fd5c9512687697a7e32b56477bb28 go version go1.10.3) to the latest versions.

But i have this problem:
```
Error occurred at instruction 50 {s2i, <nil>}, originating in rules.mtail at line 17
Full input text from "testdata/mtailstats.log" was "0.000|200|-|12072|HIT|-|-"
I0428 09:16:09.537333   95410 vm.go:109] Set logging verbosity higher (-v1 or more) to see full VM state dump.
I0428 09:16:09.537384   95410 vm.go:107] rules.mtail: Runtime error: strconv.ParseInt: parsing "-": invalid syntax
```

Start mtail:

```
MacBook-Air-de-Admin:mtail rafael.cirolini$ ./mtail_v3.0.0-rc35_darwin_amd64 -logtostderr --progs ./progs --logs testdata/mtailstats.log
I0428 09:20:09.786965   95587 main.go:103] mtail version v3.0.0-rc35 git revision a33283598c4b7a70fc2f113680318f29d5826cca go version go1.14 go arch amd64 go os darwin
I0428 09:20:09.787093   95587 main.go:104] Commandline: ["./mtail_v3.0.0-rc35_darwin_amd64" "-logtostderr" "--progs" "./progs" "--logs" "testdata/mtailstats.log"]
I0428 09:20:09.788181   95587 log_watcher.go:249] No abspath in watched list, added new one for /Users/rafael.cirolini/Desktop/projetos/mtail/progs
I0428 09:20:09.788785   95587 checker.go:217] declaration of capture group reference `proxy_status' at rules.mtail:10:5-255 appears to be unused
I0428 09:20:09.788809   95587 checker.go:217] declaration of capture group reference `proxy_status' at rules.mtail:10:5-255 appears to be unused
I0428 09:20:09.789107   95587 loader.go:229] Loaded program rules.mtail
I0428 09:20:09.789323   95587 log_watcher.go:249] No abspath in watched list, added new one for /Users/rafael.cirolini/Desktop/projetos/mtail/testdata
I0428 09:20:09.789396   95587 log_watcher.go:249] No abspath in watched list, added new one for /Users/rafael.cirolini/Desktop/projetos/mtail/testdata/mtailstats.log
I0428 09:20:09.789417   95587 log_watcher.go:254] Found this processor in watched list
I0428 09:20:09.789471   95587 log_watcher.go:254] Found this processor in watched list
I0428 09:20:09.789493   95587 tail.go:302] Tailing /Users/rafael.cirolini/Desktop/projetos/mtail/testdata/mtailstats.log
I0428 09:20:09.789554   95587 store.go:136] Starting metric store expiry loop every 1h0m0s
I0428 09:20:09.789560   95587 tail.go:448] Starting log handle expiry loop every 1h0m0s
I0428 09:20:09.789585   95587 mtail.go:321] Listening on [::]:3903
```

My progs:

```
$ cat ./progs/rules.mtail
counter nginx_request_duration_bucket by le
counter nginx_request_duration_sum
counter nginx_request_bytes_sent_sum
counter nginx_requests by status, upstream_cache_status, nginx_upstream_requests_status
counter nginx_upstream_requests_status by status
counter nginx_upstream_response_bucket by le

getfilename() =~ /mtailstats.log/ {

    /^(?P<request_time>\d+\.\d+)\|(?P<status>[1-5][0-9][0-9])\|(?P<proxy_status>[1-5][0-9][0-9]|\-)\|(?P<bytes_sent>\d+)\|(?P<upstream_cache_status>[1-5][0-9][0-9]|\-|\w+)\|(?P<upstream_status>[1-5][0-9][0-9]|\-)\|(?P<upstream_response_time>\d+\.\d+|\-)$/ {
        $request_time <= 0.005 {
            nginx_request_duration_bucket["0"]++
        }
        nginx_request_duration_bucket["+Inf"]++
        nginx_request_duration_sum += $request_time
        nginx_request_bytes_sent_sum += $bytes_sent
        nginx_requests[$status][$upstream_cache_status][$upstream_status]++
        nginx_upstream_requests_status[$upstream_status]++
        $upstream_response_time != "-" {
            $upstream_response_time <= 0.005 {
                nginx_upstream_response_bucket["0"]++
            }
            nginx_upstream_response_bucket["+Inf"]++
        }
    }
}
```

testdata.log
```
$ cat testdata/mtailstats.log
0.000|200|-|1518|HIT|-|-
0.000|200|-|12072|HIT|-|-
0.000|200|-|740|HIT|-|-
0.000|200|-|655|HIT|-|-
0.000|304|-|303|HIT|-|-
0.043|200|-|2595|-|200|0.043
0.177|200|-|169|-|200|0.176
0.000|200|-|12072|HIT|-|-
0.000|200|-|1632|HIT|-|-
0.163|200|-|18015|MISS|200|0.164
```

In the version v3.0.0-rc23 i have this error:

```
I0428 09:23:11.624003   95623 vm.go:80] rules.mtail: Runtime error: strconv.ParseInt: parsing "-": invalid syntax
I0428 09:23:11.624047   95623 vm.go:81] VM stack:
goroutine 9 [running]:
runtime/debug.Stack(0xc0004d36e8, 0x1f, 0xc0004d3c50)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/google/mtail/internal/vm.(*VM).errorf(0xc0001643c0, 0x147b4c3, 0x2, 0xc0004d3c50, 0x1, 0x1)
	/go/src/github.com/google/mtail/internal/vm/vm.go:81 +0x113
github.com/google/mtail/internal/vm.(*VM).execute(0xc0001643c0, 0xc00015e410, 0x34, 0x0, 0x0)
	/go/src/github.com/google/mtail/internal/vm/vm.go:665 +0x2c43
github.com/google/mtail/internal/vm.(*VM).processLine(0xc0001643c0, 0xc0004552c0)
	/go/src/github.com/google/mtail/internal/vm/vm.go:734 +0x140
github.com/google/mtail/internal/vm.(*VM).Run(0xc0001643c0, 0x72756c65, 0xc000150420, 0xc000150480, 0xc0001504e0)
	/go/src/github.com/google/mtail/internal/vm/vm.go:753 +0xf5
created by github.com/google/mtail/internal/vm.(*Loader).CompileAndRun
	/go/src/github.com/google/mtail/internal/vm/loader.go:240 +0x70d
I0428 09:23:11.624104   95623 vm.go:82] Dumping vm state
I0428 09:23:11.624114   95623 vm.go:83] Name: rules.mtail
I0428 09:23:11.624214   95623 vm.go:84] Input: &logline.LogLine{Filename:"testdata/mtailstats.log", Line:"0.000|304|-|303|HIT|-|-"}
I0428 09:23:11.624238   95623 vm.go:85] Thread:
I0428 09:23:11.624248   95623 vm.go:86]  PC 50
I0428 09:23:11.624271   95623 vm.go:87]  Matched true
I0428 09:23:11.624280   95623 vm.go:88]  Matches map[1:[0.000|304|-|303|HIT|-|- 0.000 304 - 303 HIT - -] 0:[mtailstats.log]]
I0428 09:23:11.624302   95623 vm.go:89]  Timestamp 0001-01-01 00:00:00 +0000 UTC
I0428 09:23:11.624331   95623 vm.go:90]  Stack [304 HIT]
I0428 09:23:11.624729   95623 vm.go:91] Prog: rules.mtail
Metrics
        0 Metric: name=nginx_request_duration_bucket program=rules.mtail kind=Counter type=Int hidden=false keys=[le] labelvalues=[LabelValue: [0] 778@1588076591623988000 LabelValue: [+Inf] 1238@1588076591623990000] source=rules.mtail:1:9-37
        1 Metric: name=nginx_request_duration_sum program=rules.mtail kind=Counter type=Float hidden=false keys=[] labelvalues=[LabelValue: [] 411.0540000000001@1588076591623993000] source=rules.mtail:2:9-34
        2 Metric: name=nginx_request_bytes_sent_sum program=rules.mtail kind=Counter type=Int hidden=false keys=[] labelvalues=[LabelValue: [] 25482666@1588076591623995000] source=rules.mtail:3:9-36
        3 Metric: name=nginx_requests program=rules.mtail kind=Counter type=Int hidden=false keys=[status upstream_cache_status nginx_upstream_requests_status] labelvalues=[LabelValue: [200 - 200] 171@1588076591615336000 LabelValue: [200 MISS 200] 69@1588076591617173000 LabelValue: [200 BYPASS 200] 117@1588076591461364000 LabelValue: [200 EXPIRED 200] 48@1588076591329032000 LabelValue: [500 BYPASS 500] 2@1588076591282633000 LabelValue: [404 MISS 404] 4@1588076591125975000 LabelValue: [201 - 201] 1@1588076591043296000 LabelValue: [404 BYPASS 404] 6@1588076591282664000 LabelValue: [200 REVALIDATED 304] 13@1588076591459666000 LabelValue: [502 MISS 502] 1@1588076591088821000 LabelValue: [301 MISS 301] 1@1588076591091390000 LabelValue: [302 MISS 302] 1@1588076591107736000 LabelValue: [403 EXPIRED 403] 3@1588076591115065000 LabelValue: [304 MISS 200] 1@1588076591158612000 LabelValue: [204 BYPASS 204] 1@1588076591223116000 LabelValue: [502 - 502] 1@1588076591233978000 LabelValue: [304 REVALIDATED 304] 1@1588076591253555000 LabelValue: [304 BYPASS 200] 2@1588076591338890000 LabelValue: [500 MISS 500] 1@1588076591290244000] source=rules.mtail:4:9-22
        4 Metric: name=nginx_upstream_requests_status program=rules.mtail kind=Counter type=Int hidden=false keys=[status] labelvalues=[LabelValue: [200] 408@1588076591617175000 LabelValue: [500] 3@1588076591290247000 LabelValue: [404] 10@1588076591282666000 LabelValue: [201] 1@1588076591043299000 LabelValue: [304] 14@1588076591459668000 LabelValue: [502] 2@1588076591233980000 LabelValue: [301] 1@1588076591091394000 LabelValue: [302] 1@1588076591107740000 LabelValue: [403] 3@1588076591115067000 LabelValue: [204] 1@1588076591223120000] source=rules.mtail:5:9-38
        5 Metric: name=nginx_upstream_response_bucket program=rules.mtail kind=Counter type=Int hidden=false keys=[le] labelvalues=[LabelValue: [+Inf] 444@1588076591617182000 LabelValue: [0] 1@1588076591107839000] source=rules.mtail:6:9-38
Regexps
        0 /mtailstats.log/
        1 /^(?P<request_time>\d+\.\d+)\|(?P<status>[1-5][0-9][0-9])\|(?P<proxy_status>[1-5][0-9][0-9]|\-)\|(?P<bytes_sent>\d+)\|(?P<upstream_cache_status>[1-5][0-9][0-9]|\-|\w+)\|(?P<upstream_status>[1-5][0-9][0-9]|\-)\|(?P<upstream_response_time>\d+\.\d+|\-)$/
Strings
        0 "0"
        1 "+Inf"
        2 "-"
        3 "0"
        4 "+Inf"
 disasm  l          op  opnd
         0 getfilename     0
         1      smatch     0
         2         jnm    97
         3  setmatched false
         4       match     1
         5         jnm    96
         6  setmatched false
         7        push     1
         8      capref     1
         9         s2f <nil>
        10        push 0.005
        11        fcmp     1
        12          jm    15
        13        push  true
        14         jmp    16
        15        push false
        16         jnm    23
        17  setmatched false
        18         str     0
        19       mload     0
        20       dload     1
        21         inc <nil>
        22  setmatched  true
        23         str     1
        24       mload     0
        25       dload     1
        26         inc <nil>
        27       mload     1
        28       dload     0
        29       mload     1
        30       dload     0
        31        push     1
        32      capref     1
        33         s2f <nil>
        34        fadd <nil>
        35        fset <nil>
        36       mload     2
        37       dload     0
        38        push     1
        39      capref     4
        40         s2i <nil>
        41         inc     0
        42        push     1
        43      capref     2
        44         s2i <nil>
        45         i2s <nil>
        46        push     1
        47      capref     5
        48        push     1
        49      capref     6
        50         s2i <nil>
        51         i2s <nil>
        52       mload     3
        53       dload     3
        54         inc <nil>
        55        push     1
        56      capref     6
        57         s2i <nil>
        58         i2s <nil>
        59       mload     4
        60       dload     1
        61         inc <nil>
        62        push     1
        63      capref     7
        64         s2f <nil>
        65         f2s <nil>
        66         str     2
        67        scmp     0
        68          jm    71
        69        push  true
        70         jmp    72
        71        push false
        72         jnm    95
        73  setmatched false
        74        push     1
        75      capref     7
        76         s2f <nil>
        77        push 0.005
        78        fcmp     1
        79          jm    82
        80        push  true
        81         jmp    83
        82        push false
        83         jnm    90
        84  setmatched false
        85         str     3
        86       mload     5
        87       dload     1
        88         inc <nil>
        89  setmatched  true
        90         str     4
        91       mload     5
        92       dload     1
        93         inc <nil>
        94  setmatched  true
        95  setmatched  true
        96  setmatched  true
```

In version v3.0.0-rc15 all works fine.

**Comment by jaqx0r** [comment]
Thanks for the detailed issue!  I think what's happened is on line 17 (per your first error) one of the `upstream_cache_status` or `$upstream_status` are declared to be of type Int, and then when you get to parsing the `-` on that input line, it fails to convert.  Those variables should be type String.

I'll download your data and confirm locally.  If my guess is correct, then something is broken in the type inference for that capture group definition in your regular expression `(?P<upstream_cache_status>[1-5][0-9][0-9]|\-|\w+)` because it shouldn't be inferring that `-` or a `\w` can be an Int.

**Comment by jaqx0r** [comment]
Can repro at HEAD with:

`./mtail --logtostderr --progs bug/rules.mtail --logs bug/mtailstats.log --one_shot --dump_ast_types --dump_bytecode`

The program around instr 50 is:

```
        48        push     1   17
        49      capref     6   17
        50         s2i <nil>   17
        51         i2s <nil>   17
```

which says capture gourp ref 6 in regex 1; the bytecode dump tells me that it's the `(?P<upstream_status>` field.

This field does not match a `\w`, unlike the upstream_cache_status field.

I can see from the AST dump that the type of nginx_requests isn't right:
```
 ( ;;*ast.VarDecl <Int⨯String⨯Int⨯Int> @ rules.mtail:4:9-22
  counter nginx_requests (status upstream_cache_status nginx_upstream_requests_status))
```

That should be Int x String x String x Int but I think the type inference is assuming a `-` by itself is still an Int.

**Comment by jaqx0r** [comment]
Yep, the type inference is checking that the regexp `\-|[0-9]` matches only int-looking things, and returns true, but can't tell that the - and the 0-9 are on different sides of the alternation, and what that means for "int-ness"

internal/vm/types/types.go:407 is the error.  groupOnlyMatches() needs to recurse the group structure with parts of the InferCaprefType function from types.go:404
