### ISSUE TITLE
Metrics stop being updated after VM's Runtime error

### ISSUE THREAD

**Issue by filippog** [google/mtail#50]
Hi,
we've observed mtail stop updating its exported metrics (and e.g. stop pushing to graphite) after a parse error has been encountered, in this form:

```
I1108 04:32:57.161927   16726 vm.go:176] Runtime error: conversion of "kernel: [1614712.454448] EDAC MC1: 1 CE" to numeric failed: strconv.ParseInt: parsing "kernel: [1614712.454448] EDAC MC1: 1 CE": invalid syntax
I1108 04:32:57.162025   16726 vm.go:177] VM stack:
goroutine 23 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
/usr/lib/go-1.6/src/runtime/debug/stack.go:24 +0x80
github.com/google/mtail/vm.(*VM).errorf(0xc8201bebe0, 0x926478, 0x2, 0xc820205bd8, 0x1, 0x1)
/home/filippo/.go/src/github.com/google/mtail/vm/vm.go:177 +0xca
github.com/google/mtail/vm.(*VM).execute(0xc8201bebe0, 0xc820b76af0, 0xd, 0x0, 0x0)
/home/filippo/.go/src/github.com/google/mtail/vm/vm.go:382 +0x2c69
github.com/google/mtail/vm.(*VM).processLine(0xc8201bebe0, 0xc820cbcc00, 0xfd)
/home/filippo/.go/src/github.com/google/mtail/vm/vm.go:612 +0x1d1
github.com/google/mtail/vm.(*VM).Run(0xc8201bebe0, 0xc8200818c0, 0xc820081920)
/home/filippo/.go/src/github.com/google/mtail/vm/vm.go:626 +0x1a2
created by github.com/google/mtail/vm.(*Loader).CompileAndRun
/home/filippo/.go/src/github.com/google/mtail/vm/loader.go:130 +0x956
I1108 04:32:57.162040   16726 vm.go:178] Dumping vm state
I1108 04:32:57.162049   16726 vm.go:179] Name: kernel.mtail
I1108 04:32:57.162061   16726 vm.go:180] Input: "Nov  8 04:32:57 mw2213 kernel: [1614712.454448] EDAC MC1: 1 CE memory scrubbing error on CPU_SrcID#1_Ha#0_Chan#1_DIMM#0 (channel:1 slot:0 page:0x9a0b7a offset:0x0 grain:32 syndrome:0x0 -  area:DRAM err_code:0008:00c2 socket:1 ha:0 channel_mask:2 rank:0)"
I1108 04:32:57.162081   16726 vm.go:181] Regexes:
I1108 04:32:57.162090   16726 vm.go:183] #011   0 (?P<date>(?P<legacy_date>\w+\s+\d+\s+\d+:\d+:\d+)|(?P<rfc3339_date>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d+[+-]\d{2}:\d{2}))\s+(?:\w+@)?(?P<hostname>[\w\.-]+)\s+(?P<application>[\w\.-]+)(?:\[(?P<pid>\d+)\])?:\s+(?P<message>.*)
I1108 04:32:57.162111   16726 vm.go:183] #011   1 kernel: \[[\d.]+\] mce: .*Machine check events logged
I1108 04:32:57.162136   16726 vm.go:183] #011   2 kernel: \[[\d.]+\] .* above threshold, cpu clock throttled
I1108 04:32:57.162145   16726 vm.go:183] #011   3 kernel: \[[\d.]+\] EDAC
I1108 04:32:57.162153   16726 vm.go:183] #011   4 kernel: \[[\d.]+\] EDAC MC\d+: (\d+) CE
I1108 04:32:57.162162   16726 vm.go:183] #011   5 kernel: \[[\d.]+\] EDAC MC\d+: (\d+) UE
I1108 04:32:57.162171   16726 vm.go:183] #011   6 kernel: \[[\d.]+\] init: (?P<service>[\S]+) .*process ended, respawning
I1108 04:32:57.162180   16726 vm.go:183] #011   7 kernel: \[[\d.]+\] (?P<binary>[\S]+) invoked oom-killer:.*
I1108 04:32:57.162189   16726 vm.go:183] #011   8 kernel: \[[\d.]+\] (?P<binary>[^\[]+)\[\d+\]: segfault at.*
I1108 04:32:57.162198   16726 vm.go:185] Strings:
I1108 04:32:57.162205   16726 vm.go:187] #011   0 "Jan _2 15:04:05"
I1108 04:32:57.162215   16726 vm.go:187] #011   1 "2006-01-02T03:04:05-0700"
I1108 04:32:57.162224   16726 vm.go:189] Thread:
I1108 04:32:57.162232   16726 vm.go:190] #011PC 57
I1108 04:32:57.162240   16726 vm.go:191] #011Match true
I1108 04:32:57.162248   16726 vm.go:192] #011Matched false
I1108 04:32:57.162255   16726 vm.go:193] #011Matches map[2:[] 3:[kernel: [1614712.454448] EDAC ] 4:[kernel: [1614712.454448] EDAC MC1: 1 CE 1] 0:[Nov  8 04:32:57 mw2213 kernel: [1614712.454448] EDAC MC1: 1 CE memory scrubbing error on CPU_SrcID#1_Ha#0_Chan#1_DIMM#0 (channel:1 slot:0 page:0x9a0b7a offset:0x0 grain:32 syndrome:0x0 -  area:DRAM err_code:0008:00c2 socket:1 ha:0 channel_mask:2 rank:0) Nov  8 04:32:57 Nov  8 04:32:57  mw2213 kernel  [1614712.454448] EDAC MC1: 1 CE memory scrubbing error on CPU_SrcID#1_Ha#0_Chan#1_DIMM#0 (channel:1 slot:0 page:0x9a0b7a offset:0x0 grain:32 syndrome:0x0 -  area:DRAM err_code:0008:00c2 socket:1 ha:0 channel_mask:2 rank:0)] 1:[]]
I1108 04:32:57.162353   16726 vm.go:194] #011Timestamp 2016-11-08 04:32:57 +0000 UTC
I1108 04:32:57.162381   16726 vm.go:195] #011Stack [0@0 0@0]
I1108 04:32:57.162402   16726 vm.go:196] Program:
I1108 04:32:57.162413   16726 vm.go:204]   #011   0        match 0
I1108 04:32:57.162427   16726 vm.go:204]   #011   1          jnm 100
I1108 04:32:57.162451   16726 vm.go:204]   #011   2   setmatched false
I1108 04:32:57.162462   16726 vm.go:204]   #011   3         push 0
I1108 04:32:57.162471   16726 vm.go:204]   #011   4       capref 2
I1108 04:32:57.162481   16726 vm.go:204]   #011   5       length 1
I1108 04:32:57.162490   16726 vm.go:204]   #011   6         push 0
I1108 04:32:57.162499   16726 vm.go:204]   #011   7          cmp 1
I1108 04:32:57.162511   16726 vm.go:204]   #011   8          jnm 15
I1108 04:32:57.162520   16726 vm.go:204]   #011   9   setmatched false
I1108 04:32:57.162530   16726 vm.go:204]   #011  10         push 0
I1108 04:32:57.162540   16726 vm.go:204]   #011  11       capref 1
I1108 04:32:57.162549   16726 vm.go:204]   #011  12          str 0
I1108 04:32:57.162558   16726 vm.go:204]   #011  13     strptime 2
I1108 04:32:57.162568   16726 vm.go:204]   #011  14   setmatched true
I1108 04:32:57.162577   16726 vm.go:204]   #011  15         push 0
I1108 04:32:57.162586   16726 vm.go:204]   #011  16       capref 3
I1108 04:32:57.162595   16726 vm.go:204]   #011  17       length 1
I1108 04:32:57.162604   16726 vm.go:204]   #011  18         push 0
I1108 04:32:57.162614   16726 vm.go:204]   #011  19          cmp 1
I1108 04:32:57.162623   16726 vm.go:204]   #011  20          jnm 27
I1108 04:32:57.162632   16726 vm.go:204]   #011  21   setmatched false
I1108 04:32:57.162641   16726 vm.go:204]   #011  22         push 0
I1108 04:32:57.162664   16726 vm.go:204]   #011  23       capref 3
I1108 04:32:57.162674   16726 vm.go:204]   #011  24          str 1
I1108 04:32:57.162683   16726 vm.go:204]   #011  25     strptime 2
I1108 04:32:57.162693   16726 vm.go:204]   #011  26   setmatched true
I1108 04:32:57.162703   16726 vm.go:204]   #011  27        match 1
I1108 04:32:57.162713   16726 vm.go:204]   #011  28          jnm 34
I1108 04:32:57.162722   16726 vm.go:204]   #011  29   setmatched false
I1108 04:32:57.162732   16726 vm.go:204]   #011  30        mload 0
I1108 04:32:57.162742   16726 vm.go:204]   #011  31        dload 0
I1108 04:32:57.162752   16726 vm.go:204]   #011  32          inc <nil>
I1108 04:32:57.162762   16726 vm.go:204]   #011  33   setmatched true
I1108 04:32:57.162772   16726 vm.go:204]   #011  34        match 2
I1108 04:32:57.162783   16726 vm.go:204]   #011  35          jnm 41
I1108 04:32:57.162793   16726 vm.go:204]   #011  36   setmatched false
I1108 04:32:57.162803   16726 vm.go:204]   #011  37        mload 1
I1108 04:32:57.162813   16726 vm.go:204]   #011  38        dload 0
I1108 04:32:57.162822   16726 vm.go:204]   #011  39          inc <nil>
I1108 04:32:57.162832   16726 vm.go:204]   #011  40   setmatched true
I1108 04:32:57.162841   16726 vm.go:204]   #011  41        match 3
I1108 04:32:57.162851   16726 vm.go:204]   #011  42          jnm 48
I1108 04:32:57.162861   16726 vm.go:204]   #011  43   setmatched false
I1108 04:32:57.162870   16726 vm.go:204]   #011  44        mload 4
I1108 04:32:57.162880   16726 vm.go:204]   #011  45        dload 0
I1108 04:32:57.162889   16726 vm.go:204]   #011  46          inc <nil>
I1108 04:32:57.162899   16726 vm.go:204]   #011  47   setmatched true
I1108 04:32:57.162909   16726 vm.go:204]   #011  48        match 4
I1108 04:32:57.162933   16726 vm.go:204]   #011  49          jnm 60
I1108 04:32:57.162945   16726 vm.go:204]   #011  50   setmatched false
I1108 04:32:57.162968   16726 vm.go:204]   #011  51        mload 2
I1108 04:32:57.162977   16726 vm.go:204]   #011  52        dload 0
I1108 04:32:57.162987   16726 vm.go:204]   #011  53        mload 2
I1108 04:32:57.162996   16726 vm.go:204]   #011  54        dload 0
I1108 04:32:57.163005   16726 vm.go:204]   #011  55         push 4
I1108 04:32:57.163015   16726 vm.go:204]   #011  56       capref 0
I1108 04:32:57.163024   16726 vm.go:204]  *#011  57          add <nil>
I1108 04:32:57.163033   16726 vm.go:204]   #011  58          set <nil>
I1108 04:32:57.163042   16726 vm.go:204]   #011  59   setmatched true
I1108 04:32:57.163052   16726 vm.go:204]   #011  60        match 5
I1108 04:32:57.163061   16726 vm.go:204]   #011  61          jnm 72
I1108 04:32:57.163072   16726 vm.go:204]   #011  62   setmatched false
I1108 04:32:57.163082   16726 vm.go:204]   #011  63        mload 3
I1108 04:32:57.163091   16726 vm.go:204]   #011  64        dload 0
I1108 04:32:57.163100   16726 vm.go:204]   #011  65        mload 3
I1108 04:32:57.163109   16726 vm.go:204]   #011  66        dload 0
I1108 04:32:57.163119   16726 vm.go:204]   #011  67         push 5
I1108 04:32:57.163128   16726 vm.go:204]   #011  68       capref 0
I1108 04:32:57.163137   16726 vm.go:204]   #011  69          add <nil>
I1108 04:32:57.163147   16726 vm.go:204]   #011  70          set <nil>
I1108 04:32:57.163156   16726 vm.go:204]   #011  71   setmatched true
I1108 04:32:57.163165   16726 vm.go:204]   #011  72        match 6
I1108 04:32:57.163174   16726 vm.go:204]   #011  73          jnm 81
I1108 04:32:57.163183   16726 vm.go:204]   #011  74   setmatched false
I1108 04:32:57.163192   16726 vm.go:204]   #011  75         push 6
I1108 04:32:57.163202   16726 vm.go:204]   #011  76       capref 1
I1108 04:32:57.163211   16726 vm.go:204]   #011  77        mload 5
I1108 04:32:57.163221   16726 vm.go:204]   #011  78        dload 1
I1108 04:32:57.163230   16726 vm.go:204]   #011  79          inc <nil>
I1108 04:32:57.163239   16726 vm.go:204]   #011  80   setmatched true
I1108 04:32:57.163249   16726 vm.go:204]   #011  81        match 7
I1108 04:32:57.163258   16726 vm.go:204]   #011  82          jnm 90
I1108 04:32:57.163267   16726 vm.go:204]   #011  83   setmatched false
I1108 04:32:57.163277   16726 vm.go:204]   #011  84         push 7
I1108 04:32:57.163286   16726 vm.go:204]   #011  85       capref 1
I1108 04:32:57.163295   16726 vm.go:204]   #011  86        mload 6
I1108 04:32:57.163304   16726 vm.go:204]   #011  87        dload 1
I1108 04:32:57.163314   16726 vm.go:204]   #011  88          inc <nil>
I1108 04:32:57.163325   16726 vm.go:204]   #011  89   setmatched true
I1108 04:32:57.163334   16726 vm.go:204]   #011  90        match 8
I1108 04:32:57.163344   16726 vm.go:204]   #011  91          jnm 99
I1108 04:32:57.163353   16726 vm.go:204]   #011  92   setmatched false
I1108 04:32:57.163362   16726 vm.go:204]   #011  93         push 8
I1108 04:32:57.163371   16726 vm.go:204]   #011  94       capref 1
I1108 04:32:57.163380   16726 vm.go:204]   #011  95        mload 7
I1108 04:32:57.163389   16726 vm.go:204]   #011  96        dload 1
I1108 04:32:57.163398   16726 vm.go:204]   #011  97          inc <nil>
I1108 04:32:57.163407   16726 vm.go:204]   #011  98   setmatched true
I1108 04:32:57.163416   16726 vm.go:204]   #011  99   setmatched true
I1108 04:33:02.043236   16726 export.go:119] pushing to graphite-in.eqiad.wmnet:2003
I1108 04:33:02.043908   16726 export.go:104] Sent 54 bytes
```

Note that the `pushing to graphite` keeps happening but graphite on the end reports all `null`, ditto for prometheus metrics: values reported are stuck to those before the error.

**Comment by jaqx0r** [comment]
That's by design but I can see now how that is annoying.

**Comment by gi11es** [comment]
You mean that not recovering from the parse error is by design, not the actual parse error encountered here, right?

**Comment by jaqx0r** [comment]
The parse looks like a bug in the mtail program being executed by the vm.
The vm has always terminated execution of a program on an error like this,
to make it easier to debug. But I recognise that is annoying and the
program could be restarted instead, still logging the error for diagnosis
later.

**Comment by jaqx0r** [comment]
Or to put in another way, it is time to transition mtail from a debug
oriented pattern of fail stop to a production oriented pattern of recovery
and continuous operation.

**Comment by filippog** [comment]
Agree @jaqx0r that was surprising ! It might make sense to have the user chose what to do on parse failure.

Case in point though I'm failing to see why a bigger match is tried to be converted to int, the whole program looks like this: https://github.com/wikimedia/operations-puppet/commit/8ec2656b137c697ebd1aad10cd630950453ae91b#diff-3b100409105416d43f601f4c0f1e79f5

**Comment by filippog** [comment]
We've got sort-of a reoccurence of this where metrics would stop being pushed to graphite and logfiles being followed at all, though I couldn't find a VM crash in the logs at the time. Full goroutine dump is also available at https://phabricator.wikimedia.org/T149980#2796528

**Comment by jaqx0r** [comment]
Thanks for the dump!

**Comment by jaqx0r** [comment]
Very simply I think the terminate flag needed to be reset so the next pass through that VM doesn't exit immediately,  Please try this out and let me know how you go.

**Comment by jaqx0r** [comment]
OK I think this is properly fixed again.  I got confused as to why the flag needed to be reset.
