### ISSUE TITLE
Panic when a key is missing

### ISSUE THREAD

**Issue by hephex** [google/mtail#73]
If a key is missing when a metric is used in an action, mtail stops with a runtime error.

i.e.
prog:
```
counter n by method, time

/(?P<method>.*) (?P<time>\d+\.\d+)/ {
    n[$time]++
}
```

output:
```
panic: runtime error: index out of range

goroutine 23 [running]:
github.com/google/mtail/vm.(*VM).execute(0xc42019a280, 0xc42008a640, 0x1a, 0x7b34a0, 0xc42014c5f8)
        /home/test/go/src/github.com/google/mtail/vm/vm.go:600 +0x44a
github.com/google/mtail/vm.(*VM).processLine(0xc42019a280, 0xc420017cb0, 0xa)
        /home/test/go/src/github.com/google/mtail/vm/vm.go:676 +0x17a
github.com/google/mtail/vm.(*VM).Run(0xc42019a280, 0x74657374, 0xc420080780, 0xc4200807e0)
        /home/test/go/src/github.com/google/mtail/vm/vm.go:692 +0x138
created by github.com/google/mtail/vm.(*Loader).CompileAndRun
```

It would nice catching this error at compile time. Do you think it would be possible?

**Comment by jaqx0r** [comment]
Yeah.  We should figure out that the metric has two dimensions during the type check.  Thanks!

**Comment by jaqx0r** [comment]
This should be fixed now, but I see I forgot to tag the commit.
