### ISSUE TITLE
statsd exporter crashes when no metrics are available for export

### ISSUE THREAD

**Issue by davidreuss** [google/mtail#8]
Below is crash dump, the program was run with: 

```
$ mtail --logs timings.txt --progs timers --alsologtostderr=true -metric_push_interval_seconds=5 -statsd_hostport=localhost:8125
```

dump:

```
I0729 20:40:24.908709    1647 tail.go:297] Tailing /Users/david/Projects/go/src/github.com/google/mtail/timings.txt
I0729 20:40:24.909750    1647 export.go:154] Started metric push.
I0729 20:40:24.909797    1647 mtail.go:209] Listening on port 3903
panic: interface conversion: interface is nil, not time.Time

goroutine 19 [running]:
github.com/google/mtail/exporter.(*Exporter).WriteMetrics(0xc20802c7d0)
	/Users/david/Projects/go/src/github.com/google/mtail/exporter/export.go:131 +0x78
github.com/google/mtail/exporter.func·002()
	/Users/david/Projects/go/src/github.com/google/mtail/exporter/export.go:160 +0x74
created by github.com/google/mtail/exporter.(*Exporter).StartMetricPush
	/Users/david/Projects/go/src/github.com/google/mtail/exporter/export.go:163 +0x1d3

goroutine 1 [select]:
github.com/google/mtail/mtail.(*Mtail).shutdownHandler(0xc20807c0e0)
	/Users/david/Projects/go/src/github.com/google/mtail/mtail/mtail.go:232 +0x3e0
github.com/google/mtail/mtail.(*Mtail).Serve(0xc20807c0e0)
	/Users/david/Projects/go/src/github.com/google/mtail/mtail/mtail.go:215 +0x3d8
github.com/google/mtail/mtail.(*Mtail).Run(0xc20807c0e0)
	/Users/david/Projects/go/src/github.com/google/mtail/mtail/mtail.go:263 +0x42
main.main()
	/Users/david/Projects/go/src/github.com/google/mtail/main.go:70 +0x852

goroutine 6 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x5eab40)
	/Users/david/Projects/go/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
	/Users/david/Projects/go/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 8 [syscall]:
os/signal.loop()
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:27 +0x35

goroutine 9 [syscall]:
syscall.Syscall6(0x16b, 0x3, 0x0, 0x0, 0xc208018690, 0xa, 0x5f3570, 0x5761, 0xc2080422bc, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/asm_darwin_amd64.s:44 +0x5
syscall.kevent(0x3, 0x0, 0x0, 0xc208018690, 0xa, 0x5f3570, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/zsyscall_darwin_amd64.go:200 +0x81
syscall.Kevent(0x3, 0x0, 0x0, 0x0, 0xc208018690, 0xa, 0xa, 0x5f3570, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/syscall_bsd.go:480 +0x9b
gopkg.in/fsnotify%2ev1.read(0x3, 0xc208018690, 0xa, 0xa, 0x5f3570, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/david/Projects/go/src/gopkg.in/fsnotify.v1/kqueue.go:453 +0xab
gopkg.in/fsnotify%2ev1.(*Watcher).readEvents(0xc208042300)
	/Users/david/Projects/go/src/gopkg.in/fsnotify.v1/kqueue.go:262 +0x1a2
created by gopkg.in/fsnotify%2ev1.NewWatcher
	/Users/david/Projects/go/src/gopkg.in/fsnotify.v1/kqueue.go:61 +0x31f

goroutine 10 [chan receive]:
github.com/google/mtail/watcher.(*LogWatcher).run(0xc20802aab0)
	/Users/david/Projects/go/src/github.com/google/mtail/watcher/log_watcher.go:46 +0xf6
created by github.com/google/mtail/watcher.NewLogWatcher
	/Users/david/Projects/go/src/github.com/google/mtail/watcher/log_watcher.go:29 +0xf0

goroutine 11 [chan receive]:
github.com/google/mtail/vm.(*Loader).processEvents(0xc208042480)
	/Users/david/Projects/go/src/github.com/google/mtail/vm/loader.go:198 +0xde
created by github.com/google/mtail/vm.NewLoader
	/Users/david/Projects/go/src/github.com/google/mtail/vm/loader.go:184 +0x44b

goroutine 12 [chan receive]:
github.com/google/mtail/vm.(*Loader).processLines(0xc208042480, 0xc208042060)
	/Users/david/Projects/go/src/github.com/google/mtail/vm/loader.go:218 +0x71
created by github.com/google/mtail/vm.NewLoader
	/Users/david/Projects/go/src/github.com/google/mtail/vm/loader.go:185 +0x472

goroutine 13 [syscall]:
syscall.Syscall6(0x16b, 0x6, 0x0, 0x0, 0xc20801c690, 0xa, 0x5f3570, 0x5761, 0xc208042bbc, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/asm_darwin_amd64.s:44 +0x5
syscall.kevent(0x6, 0x0, 0x0, 0xc20801c690, 0xa, 0x5f3570, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/zsyscall_darwin_amd64.go:200 +0x81
syscall.Kevent(0x6, 0x0, 0x0, 0x0, 0xc20801c690, 0xa, 0xa, 0x5f3570, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/syscall_bsd.go:480 +0x9b
gopkg.in/fsnotify%2ev1.read(0x6, 0xc20801c690, 0xa, 0xa, 0x5f3570, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/david/Projects/go/src/gopkg.in/fsnotify.v1/kqueue.go:453 +0xab
gopkg.in/fsnotify%2ev1.(*Watcher).readEvents(0xc208042c00)
	/Users/david/Projects/go/src/gopkg.in/fsnotify.v1/kqueue.go:262 +0x1a2
created by gopkg.in/fsnotify%2ev1.NewWatcher
	/Users/david/Projects/go/src/gopkg.in/fsnotify.v1/kqueue.go:61 +0x31f

goroutine 14 [chan receive]:
github.com/google/mtail/watcher.(*LogWatcher).run(0xc20802b860)
	/Users/david/Projects/go/src/github.com/google/mtail/watcher/log_watcher.go:46 +0xf6
created by github.com/google/mtail/watcher.NewLogWatcher
	/Users/david/Projects/go/src/github.com/google/mtail/watcher/log_watcher.go:29 +0xf0

goroutine 15 [chan receive]:
github.com/google/mtail/tailer.(*Tailer).run(0xc208042cc0)
	/Users/david/Projects/go/src/github.com/google/mtail/tailer/tail.go:306 +0x9e
created by github.com/google/mtail/tailer.New
	/Users/david/Projects/go/src/github.com/google/mtail/tailer/tail.go:86 +0x507

goroutine 16 [chan receive]:
github.com/google/mtail/watcher.func·001()
	/Users/david/Projects/go/src/github.com/google/mtail/watcher/log_watcher.go:41 +0x6b
created by github.com/google/mtail/watcher.(*LogWatcher).run
	/Users/david/Projects/go/src/github.com/google/mtail/watcher/log_watcher.go:45 +0x9b

goroutine 18 [chan receive]:
github.com/google/mtail/watcher.func·001()
	/Users/david/Projects/go/src/github.com/google/mtail/watcher/log_watcher.go:41 +0x6b
created by github.com/google/mtail/watcher.(*LogWatcher).run
	/Users/david/Projects/go/src/github.com/google/mtail/watcher/log_watcher.go:45 +0x9b

goroutine 20 [IO wait]:
net.(*pollDesc).Wait(0xc2080103e0, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080103e0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208010380, 0x0, 0x6b1d08, 0xc20802ab90)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20803a058, 0xdf384, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc20803a058, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc2080425a0, 0x6b3998, 0xc20803a058, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc2080425a0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1718 +0x154
net/http.ListenAndServe(0xc20802ab88, 0x5, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1808 +0xba
github.com/google/mtail/mtail.func·001()
	/Users/david/Projects/go/src/github.com/google/mtail/mtail/mtail.go:210 +0x163
created by github.com/google/mtail/mtail.(*Mtail).Serve
	/Users/david/Projects/go/src/github.com/google/mtail/mtail/mtail.go:214 +0x3c5
```

**Comment by jaqx0r** [comment]
Ah this is a simple fix. If there are no metrics, the last update time is
nil so we can't compute how long it's been since last time. I don't have a
test for pushing 0 metrics :(

**Comment by jaqx0r** [comment]
I had trouble writing a reliable test for this so just committed a fix I think works -- it validates that the update time is not nil before attempting to cast it into a time.Time.

**Comment by davidreuss** [comment]
Seems like a sensible enough solution :+1:
