### ISSUE TITLE
The parser does not understand negative literals

### ISSUE THREAD

**Issue by TheTincho** [google/mtail#97]
Hey, while trying to analyse scores from spamassassin, I noticed the parser breaks when finding a negative literal:

```
$ cat test/test.mtail 
counter foo 
/(?P<bar>[+-]?[\d.]+)/ {
  $bar < -1 {
    foo++
  }
}
```
```
I0904 04:32:54.429257   27140 loader.go:106] Compile errors for test.mtail:
compile failed for test.mtail:
test.mtail:3:10: syntax error
```

Moreover, if I try to overcome this by replacing the conditional expression with `$bar + 1 < 0`, I find another bug somewhere in the VM:

```
I0904 04:38:20.127692   27261 vm.go:187] test.mtail: Runtime error: unexpected float type int64 '\x01'
I0904 04:38:20.127901   27261 vm.go:188] VM stack:
goroutine 38 [running]:
runtime/debug.Stack(0xc42019a860, 0x1e, 0xc42019ae00)
        /usr/lib/go-1.8/src/runtime/debug/stack.go:24 +0x79
github.com/google/mtail/vm.(*VM).errorf(0xc42018a1e0, 0x84b0eb, 0x2, 0xc42019ae00, 0x1, 0x1)
        github.com/google/mtail/vm/vm.go:188 +0xe1
github.com/google/mtail/vm.(*VM).execute(0xc42018a1e0, 0xc420170410, 0x21, 0x0, 0x0)
        github.com/google/mtail/vm/vm.go:545 +0x20f0
github.com/google/mtail/vm.(*VM).processLine(0xc42018a1e0, 0xc420158400)
        github.com/google/mtail/vm/vm.go:702 +0x16d
github.com/google/mtail/vm.(*VM).Run(0xc42018a1e0, 0x74657374, 0xc42015c660, 0xc42015c6c0)
        github.com/google/mtail/vm/vm.go:718 +0x119
created by github.com/google/mtail/vm.(*Loader).CompileAndRun
        github.com/google/mtail/vm/loader.go:216 +0x638
I0904 04:38:20.127966   27261 vm.go:189] Dumping vm state
I0904 04:38:20.127983   27261 vm.go:190] Name: test.mtail
I0904 04:38:20.127997   27261 vm.go:191] Input: &{xxx/mail.info Aug 29 00:20:14 HOSTNAME postfix/dnsblog[31779]: addr 181.67.2.58 listed by domain zen.spamhaus.org as 127.0.0.4}
I0904 04:38:20.128027   27261 vm.go:192] Thread:
I0904 04:38:20.128041   27261 vm.go:193]  PC 6
I0904 04:38:20.128055   27261 vm.go:194]  Match true
I0904 04:38:20.128070   27261 vm.go:195]  Matched false
I0904 04:38:20.128083   27261 vm.go:196]  Matches map[0:[29 29]]
I0904 04:38:20.128118   27261 vm.go:197]  Timestamp 0001-01-01 00:00:00 +0000 UTC
I0904 04:38:20.128162   27261 vm.go:198]  Stack [29]
I0904 04:38:20.128462   27261 vm.go:199] Prog: test.mtail
Metrics
        0 Metric: name=foo program=test.mtail kind=Counter type=Int hidden=false keys=[] labelvalues=[LabelValue: [] 0@0] source=test.mtail:1:9-11
Regexps
        0 /(?P<bar>[+-]?[\d.]+)/
Strings
 disasm  l         op  opnd
         0      match     0
         1        jnm    16
         2 setmatched false
         3       push     0
         4     capref     1
         5       push     1
         6       fadd <nil>
         7       push     0
         8        cmp    -1
         9        jnm    15
        10 setmatched false
        11      mload     0
        12      dload     0
        13        inc <nil>
        14 setmatched  true
        15 setmatched  true
```

**Comment by TheTincho** [comment]
Playing a bit more, I noticed that `$bar + 1.0 < 0` works. Once again, the type inference bites me :/

**Comment by jaqx0r** [comment]
I think the second error is a special case of #68, which I'm still working
on.    I don't think negative literals has ever worked, so thanks for
pointing it out.

**Comment by jaqx0r** [comment]
BTW fixing inference is currently blocked on me trying to figure out how to
nicely do type coercion from int to float without requiring language
extensions: either I have a bug in the type unification code I haven't
worked out yet, or the papers I'm reading are cleverer than I am.

**Comment by TheTincho** [comment]
Thanks for looking into this!

A related question that arises is: how can one know if the types make sense with this kind of issues? This seems to be working now, but I am not sure..

**Comment by jaqx0r** [comment]
89328ba fixes the negative literal parsing.

The --dump_ast_types flag will print the compilers' type annotation of the syntax tree to the log, see http://google.github.io/mtail/Troubleshooting#syntax-trees-type-information-and-virtual-machine-bytecode
